# Generated by Django 3.1.2 on 2020-12-01 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bagisci',
            name='username',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='ogretmen',
            name='username',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
