# Generated by Django 3.1.2 on 2020-12-01 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20201201_1238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bagisci',
            name='username',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ogretmen',
            name='username',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
