# Generated by Django 3.1.2 on 2020-12-23 12:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('yardim', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carousel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='carousel')),
                ('status', models.CharField(choices=[('deleted', 'Silindi'), ('draft', 'Taslak'), ('published', 'Yayinlandi')], default='draft', max_length=10)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('uptated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='ihtiyac',
            name='city',
            field=models.CharField(max_length=50, verbose_name='Şehir'),
        ),
        migrations.AlterField(
            model_name='ihtiyac',
            name='content',
            field=models.TextField(verbose_name='İhtiyaç İçeriği'),
        ),
        migrations.AlterField(
            model_name='ihtiyac',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Başlık'),
        ),
        migrations.AlterField(
            model_name='ihtiyac',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Ogretmen'),
        ),
    ]
