# Generated by Django 3.1.2 on 2020-12-23 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yardim', '0002_auto_20201223_1543'),
    ]

    operations = [
        migrations.AddField(
            model_name='ihtiyac',
            name='sum',
            field=models.FloatField(default=200.0, verbose_name='Maliyet'),
        ),
        migrations.AlterField(
            model_name='carousel',
            name='status',
            field=models.CharField(choices=[('published', 'Yayinlandi'), ('deleted', 'Silindi'), ('draft', 'Taslak')], default='draft', max_length=10),
        ),
    ]
