# Generated by Django 3.1.2 on 2020-12-26 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yardim', '0003_auto_20201223_2133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carousel',
            name='status',
            field=models.CharField(choices=[('draft', 'Taslak'), ('published', 'Yayinlandi'), ('deleted', 'Silindi')], default='draft', max_length=10),
        ),
        migrations.AlterField(
            model_name='ihtiyac',
            name='sum',
            field=models.FloatField(verbose_name='Maliyet'),
        ),
    ]
