# Generated by Django 3.1.2 on 2020-12-30 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yardim', '0005_auto_20201226_1418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carousel',
            name='status',
            field=models.CharField(choices=[('published', 'Yayinlandi'), ('deleted', 'Silindi'), ('draft', 'Taslak')], default='draft', max_length=10),
        ),
    ]
