# Generated by Django 3.1.2 on 2020-12-31 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yardim', '0006_auto_20201230_2058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carousel',
            name='status',
            field=models.CharField(choices=[('deleted', 'Silindi'), ('draft', 'Taslak'), ('published', 'Yayinlandi')], default='draft', max_length=10),
        ),
    ]
