# Generated by Django 3.1.2 on 2021-01-04 13:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('yardim', '0008_auto_20210104_1401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bagis',
            name='ihtiyac',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='yardim.ihtiyac'),
        ),
        migrations.AlterField(
            model_name='carousel',
            name='status',
            field=models.CharField(choices=[('draft', 'Taslak'), ('published', 'Yayinlandi'), ('deleted', 'Silindi')], default='draft', max_length=10),
        ),
        migrations.CreateModel(
            name='BagisPayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=15)),
                ('last_name', models.CharField(max_length=20)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('tutar', models.FloatField()),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('tip', models.IntegerField()),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
