# Generated by Django 3.1.2 on 2021-01-21 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yardim', '0009_auto_20210104_1612'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('konu', models.CharField(max_length=50)),
                ('mesaj', models.TextField()),
            ],
        ),
    ]
